{{- $secretKeys := .Values.backend.secretKeys | default (list) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wafflebear.fullname" . }}-backend-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.backend.env }}
{{- if has $key $secretKeys }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
{{- end }}
{{- end }}
