apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wafflebear.fullname" . }}-websocket-env
data:
{{- range $key, $value := .Values.websocket.env }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
{{- end }}
